name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Message
        run: echo "Build Successful"

      - name: Slack Notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"GitHub Actions Build Completed Successfully 🚀"}' \
          ${{ secrets.SLACK_WEBHOOK }}
